name: Build and Push to GHCR

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Image tag'
        required: true

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # 必须要有推送权限
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ✅ 新增：清理磁盘空间（在 Docker 构建之前运行）
      - name: Clean disk space
        run: |
          echo "👉 清理临时文件以释放磁盘空间..."
          sudo df -h  # 查看当前磁盘使用情况
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc  # 删除不必要的大型缓存
          sudo apt-get clean  # 清理 APT 缓存
          sudo docker system prune -a -f  # 清理 Docker 缓存
          sudo df -h  # 再次检查磁盘空间

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}  # 使用 PAT 或 GITHUB_TOKEN

      - name: Build and push to GHCR
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            CNA_VERSION=latest
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nocobase:${{ inputs.tag_name }}-full
